src/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

 /*
  * These routes require no users to be logged in
  */

Route::get('/', 'HomeController@index');
Route::get('dashboard', 'HomeController@dashboard')->name('dashboard');
Route::get('/quick-search', 'PagesController@quickSearch')->name('quick-search');
Route::get('/noauth', 'HomeController@noauth')->name('noauth');

Route::middleware('web')->group(function() {
   Route::middleware('guest')->namespace('Auth')->group(function() {
      Route::get('/', 'LoginController@showLoginForm')->name('login.main');
     	Route::get('/login', 'LoginController@showLoginForm')->name('login.show-form');
      Route::get('/attribute', 'LoginController@attribute')->name('login.attribute');
     	Route::post('/login', 'LoginController@login')->name('login');
   });
   Route::get('/logout', 'Auth\LoginController@logout')->name('logout');
});

Route::middleware('web')->group(function() {
  Route::prefix('management')->namespace('Management')->as('management.')->group(function() {
      Route::prefix('user')->as('user.')->group(function() {
          Route::post('data', 'UserController@getData')->name('data');
          Route::delete('{id}', 'UserController@destroy')->name('show');
          Route::get('{id}', 'UserController@edit')->name('show');
          Route::get('{id}/change-password', 'UserController@changeOtherPassword')->name('other.change-password');
          Route::put('{id}/update-password', 'UserController@updateOtherPassword')->name('other.update-password');
      });
      Route::resource('user', 'UserController', ['except' => ['create', 'show']]);

     Route::get('login-history', 'UserHistoryController@showLoginHistory')->name('login-history');
     Route::post('login-history/data', 'UserHistoryController@getLoginHistoryData')->name('login-history.data');

     Route::prefix('role')->as('role.')->group(function() {
         Route::post('data', 'RoleController@getData')->name('data');
         Route::get('{id}', 'RoleController@show')->name('show');
         Route::get('auth/{id}', 'RoleController@show_auth')->name('show.auth');
         Route::post('{id}/{col}/{val}', 'RoleController@update_auth')->name('update.auth');
     });
     Route::resource('role', 'RoleController', ['except' => ['create', 'show']]);

     Route::prefix('menu')->as('menu.')->group(function() {
         Route::post('data', 'MenuController@getData')->name('data');
         Route::get('{id}', 'MenuController@show')->name('show');
     });
     Route::resource('menu', 'MenuController', ['except' => ['create', 'show']]);

     Route::prefix('company-auth')->as('company-auth.')->group(function() {
         Route::get('{company_id}', 'CompanyAuthController@getData')->name('data');
         Route::post('{id}/{sts}', 'CompanyAuthController@update')->name('update');
     });
     Route::resource('company-auth', 'CompanyAuthController', ['except' => ['create']]);
  });
});


$router->group(['prefix' => 'reports', 'namespace' => 'Reports', 'middleware' => 'auth'], function () use ($router) {
    $router->group(['prefix' => '{table}'], function () use ($router) {
        $router->get('/{import}/import', [
            'as' => 'reports.import', 'uses' => 'ReportsController@import'
        ]);
        $router->get('/{export}/view', [
            'as' => 'reports.view', 'uses' => 'ReportsController@view'
        ]);
        $router->get('/{export}/download', [
            'as' => 'reports.download', 'uses' => 'ReportsController@download'
        ]);
    });
});

$router->group(['prefix' => 'elastic-serach', 'namespace' => 'Search'], function () use ($router) {
    $router->group(['prefix' => '{table}'], function () use ($router) {
        $router->get('list', [
            'as' => 'search.list', 'uses' => 'SearchController@list'
        ]);
        $router->get('/data', [
            'as' => 'search.data', 'uses' => 'SearchController@data'
        ]);
    });
});

$router->group(['prefix' => 'master', 'namespace' => 'Master', 'middleware' => 'auth'], function () use ($router) {
    $router->group(['prefix' => '{table}'], function () use ($router) {
        $router->get('/', [
            'as' => 'master.index', 'uses' => 'MasterController@index'
        ]);
        $router->post('list', [
            'as' => 'master.list', 'uses' => 'MasterController@list'
        ]);
        $router->get('list', [
            'as' => 'master.list', 'uses' => 'MasterController@list'
        ]);
        $router->get('data/{id}', [
            'as' => 'master.data', 'uses' => 'MasterController@data'
        ]);
        $router->post('/', [
            'as' => 'master.save', 'uses' => 'MasterController@save'
        ]);
        $router->put('/{id}', [
            'as' => 'master.update', 'uses' => 'MasterController@update'
        ]);
        $router->delete('{id}', [
            'as' => 'master.delete', 'uses' => 'MasterController@delete'
        ]);
    });
});

 $router->group(['prefix' => 'clinic', 'namespace' => 'Clinic', 'middleware' => 'auth'], function () use ($router) {
     $router->group(['prefix' => '{table}'], function () use ($router) {
         $router->get('/', [
             'as' => 'clinic.index', 'uses' => 'ClinicController@index'
         ]);
         $router->post('list', [
             'as' => 'clinic.list', 'uses' => 'ClinicController@list'
         ]);
         $router->get('list', [
             'as' => 'clinic.list', 'uses' => 'ClinicController@list'
         ]);
         $router->get('data/{id}', [
             'as' => 'clinic.data', 'uses' => 'ClinicController@data'
         ]);
         $router->post('save', [
             'as' => 'clinic.save', 'uses' => 'ClinicController@save'
         ]);
         $router->post('update/{id}', [
             'as' => 'clinic.update', 'uses' => 'ClinicController@update'
         ]);
         $router->delete('{id}', [
             'as' => 'clinic.delete', 'uses' => 'ClinicController@delete'
         ]);
     });
 });

 $router->group(['prefix' => 'product', 'namespace' => 'Product'], function () use ($router) {
     $router->group(['prefix' => '{table}'], function () use ($router) {
         $router->get('/', [
             'as' => 'product.index', 'uses' => 'ProductController@index'
         ]);
         $router->post('list', [
             'as' => 'product.list', 'uses' => 'ProductController@list'
         ]);
         $router->get('list', [
             'as' => 'product.list', 'uses' => 'ProductController@list'
         ]);
         $router->get('data/{id}', [
             'as' => 'product.data', 'uses' => 'ProductController@data'
         ]);
         $router->post('save', [
             'as' => 'product.save', 'uses' => 'ProductController@save'
         ]);
         $router->post('update/{id}', [
             'as' => 'product.update', 'uses' => 'ProductController@update'
         ]);
         $router->delete('{id}', [
             'as' => 'product.delete', 'uses' => 'ProductController@delete'
         ]);
     });
 });

  $router->group(['prefix' => 'advertising', 'namespace' => 'Advertising'], function () use ($router) {
      $router->group(['prefix' => '{table}'], function () use ($router) {
          $router->get('/', [
              'as' => 'advertising.index', 'uses' => 'AdvertisingController@index'
          ]);
          $router->post('list', [
              'as' => 'advertising.list', 'uses' => 'AdvertisingController@list'
          ]);
          $router->post('detail', [
              'as' => 'advertising.detail', 'uses' => 'AdvertisingController@detail'
          ]);
          $router->get('data/{id}', [
              'as' => 'advertising.data', 'uses' => 'AdvertisingController@data'
          ]);
          $router->post('save', [
              'as' => 'advertising.save', 'uses' => 'AdvertisingController@save'
          ]);
          $router->post('update/{id}', [
              'as' => 'advertising.update', 'uses' => 'AdvertisingController@update'
          ]);
          $router->delete('{id}', [
              'as' => 'advertising.delete', 'uses' => 'AdvertisingController@delete'
          ]);
      });
  });

  $router->group(['prefix' => 'sales', 'namespace' => 'Sales'], function () use ($router) {
      $router->group(['prefix' => '{table}'], function () use ($router) {
          $router->get('/', [
              'as' => 'sales.index', 'uses' => 'SalesController@index'
          ]);
          $router->post('list', [
              'as' => 'sales.list', 'uses' => 'SalesController@list'
          ]);
          $router->post('detail', [
              'as' => 'sales.detail', 'uses' => 'SalesController@detail'
          ]);
          $router->get('data/{id}', [
              'as' => 'sales.data', 'uses' => 'SalesController@data'
          ]);
          $router->post('save', [
              'as' => 'sales.save', 'uses' => 'SalesController@save'
          ]);
          $router->post('update/{id}', [
              'as' => 'sales.update', 'uses' => 'SalesController@update'
          ]);
          $router->delete('{id}', [
              'as' => 'sales.delete', 'uses' => 'SalesController@delete'
          ]);
          $router->post('{id}', [
              'as' => 'sales.cancel', 'uses' => 'SalesController@cancel'
          ]);
      });
  });

 $router->group(['prefix' => 'warehouse', 'namespace' => 'Warehouse'], function () use ($router) {

src/app/Models/Menu.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;

class Menu extends Model
{
     protected $table = 'menus';
}

src/app/Http/Controllers/Management/CompanyAuthController.php
<?php

namespace App\Http\Controllers\Management;

use DataTables;
use Illuminate\Http\Request;
use App\Models\CompanyAuth;
use App\Http\Resources\Master\Company;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;

class CompanyAuthController extends Controller {

    public function update($id, $sts, Request $request) {
        // $module = $this->save($request);
        $data = CompanyAuth::find(str_replace('%20', ' ', $id));
        if(!$data){
          return makeResponse(200, 'error', 'fails', 'company not found!');
        }
        $data["status"] = $sts;
        $module = $data->save();
        if(!$sts){
            return makeResponse(200, 'success', 'notif_success', 'Update Company Auth '. $data->company_child .' has been disable join!');
        }
        return makeResponse(200, 'success', 'notif_success', 'Update Company Auth '. $data->company_child .' has been success join!');
    }

    public function getData($com_id, Request $request) {
         $select = Company::select(array(\DB::raw('CONCAT("'.$com_id.'","-",mst_company.id) AS id'),\DB::raw('"'.$com_id.'" AS company_id'),'mst_company.id AS company_child'))
                       ->leftJoin('company_auth', function($leftJoin)use($com_id){
                            $leftJoin->on('mst_company.id', '=', 'company_auth.company_child');
                            $leftJoin->where('company_auth.company_id',$com_id);
                        })
                        ->where('company_auth.company_id',null);
         $bindings = $select->getBindings();
         // dd(getSql($select));
         $insertQuery = 'INSERT into company_auth (company_auth.id,company_auth.company_id,company_auth.company_child) '
                        .$select->toSql();
         \DB::insert($insertQuery, $bindings);

      	$datas = CompanyAuth::select(
                        'company_auth.id',
                        'company_auth.company_id',
                        'company_auth.company_child',
                        'company_auth.status',
                        'mst_company.name as company_name'
                      )
                       ->leftJoin('mst_company', function($join){
                            $join->on('mst_company.id', '=', 'company_auth.company_child');
                        })
                       ->where('mst_company.id',"!=",'DEV')
                       ->where('company_auth.company_id',$com_id)
                       ->orderby('company_auth.company_child','ASC')
                       ->get();
        return makeResponse(200, 'success', null, $datas);
     }

     public function save($request, $data = null) {
        if (is_null($data)) {
            $data = new CompanyAuth;
        }

        if ($request->id) {
            $data->id = $request->id;
        }
        if ($request->company_id) {
            $data->company_id = $request->company_id;
        }
        if ($request->company_child) {
            $data->company_child = $request->company_child;
        }
        $data->save();

        return $data;
    }

}

src/app/Http/Controllers/Management/UserHistoryController.php
<?php

namespace App\Http\Controllers\Management;

use DataTables;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\UserLoginHistory;

class UserHistoryController extends Controller {
    public function showLoginHistory(){
        $page_title = 'User Login History';
        $page_description = 'Home/User Management/User Login History';

        return view('management.user.login-history', compact('page_title', 'page_description'));
    }

    public function getLoginHistoryData(){
        $userLoginHistory = UserLoginHistory::with('user')->select('user_login_histories.*');
        return Datatables::of($userLoginHistory)
            ->editColumn('created_at', function($userLoginHistory) {
                return $userLoginHistory->created_at->format('d M Y H:i:s');
            })
            ->make(true);
    }
}

src/resources/views/management/menu/index.blade.php
@extends('layout.default')

@section('content')
<div class="subheader py-2 {{ Metronic::printClasses('subheader', false) }}" id="kt_subheader">
  <div class="{{ Metronic::printClasses('subheader-container', false) }} d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
    <div class="d-flex align-items-baseline flex-wrap mr-5">
      <h5 class="text-dark font-weight-bold my-1 mr-5">
        Menus
      </h5>
      <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
        <li class="breadcrumb-item">
          <a href="{{ route('dashboard') }}" class="text-muted">Dashboard</a>
        </li>
        <li class="breadcrumb-item">
          <a href="{{ route('management.menu.index') }}" class="text-muted">Menus</a>
        </li>
        <li class="breadcrumb-item">
          <a href="#view" class="text-muted">View</a>
        </li>
      </ul>
    </div>
  </div>
</div>

@include('inc.error-list')
@include('inc.success-notif')
@include('inc.danger-notif')
<div class="card card-custom body-container">
  <div class="card-header bg-danger flex-wrap border-1 pt-1 pb-0 mb-2" style="min-height: 0;">
    <div class="card-title pt-1 pb-1">
      <h3 class="card-label font-weight-bolder text-white">Menus
        <div class="text-muted pt-2 font-size-lg">show Datatable from table Menus</div>
      </h3>
    </div>
    <div class="card-toolbar pt-1 pb-0">
      <a href="#" onclick="show_data('')" class="btn btn-primary font-weight-bolder" style="background-color: #1e1e2d;border-color: #0c8eff;">
        <span class="svg-icon svg-icon-md">
          <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
              <rect x="0" y="0" width="24" height="24"></rect>
              <circle fill="#000000" cx="9" cy="15" r="6"></circle>
              <path d="M8.8012943,7.00241953 C9.83837775,5.20768121 11.7781543,4 14,4 C17.3137085,4 20,6.6862915 20,10 C20,12.2218457 18.7923188,14.1616223 16.9975805,15.1987057 C16.9991904,15.1326658 17,15.0664274 17,15 C17,10.581722 13.418278,7 9,7 C8.93357256,7 8.86733422,7.00080962 8.8012943,7.00241953 Z" fill="#000000" opacity="0.3"></path>
            </g>
          </svg>
        </span>Add New
      </a>
    </div>
  </div>
  <div class="card-body pt-1">
    <table class="table table-bordered table-hover w100" cellspacing="0" id="datatable" style="width: 1070px !important;"></table>
  </div>
</div>


<!-- Modal-->
<div class="modal fade" id="modal-form" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="staticBackdrop" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-danger pt-3 pb-3">
                <h5 class="modal-title text-white bold" id="modal">New Menus</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <i aria-hidden="true" class="ki ki-close"></i>
                </button>
            </div>
            <form class="form" id="form-input" action="{{ route('management.menu.store') }}" method="POST">
              {!! csrf_field() !!}
              <input type="hidden" class="form-control form-control-sm" id="method" name="_method" placeholder="Enter method" value="POST"/>
                <div class="card-body pt-3">
                    <div class="mb-1" hidden>
                        <div class="form-group row">
                            <label class="col-lg-4 col-form-label">id</label>
                            <div class="col-lg-8">
                                <input type="text" class="form-control form-control-sm" id="id" name="id" placeholder="AUTO" value="" readonly/>
                            </div>
                        </div>
                    </div>
                    <div class="mb-2">
                        <div class="form-group row mb-0">
                            <label class="col-lg-4 col-form-label">Menu Parent</label>
                            <div class="col-lg-8">
                                <select class="form-control form-control-sm select2" id="parent_id" name="parent_id" style="width: 100%;">
                                  <option value="0" selected>Is Parent</option>
                                   @isset ($menu_parent)
                                     @foreach($menu_parent as $menu)
                                      <option value="{{ $menu->id }}">{{ $menu->name }}</option>
                                     @endforeach
                                   @endisset
                               </select>
                            </div>
                        </div>
                    </div>
                    <div class="mb-1">
                        <div class="form-group row mb-0">
                            <label class="col-lg-4 col-form-label">Menu</label>
                            <div class="col-lg-8">
                                <input type="text" class="form-control form-control-sm" id="name" name="name" placeholder="Enter Name" value=""/>
                            </div>
                        </div>
                    </div>
                    <div class="mb-1">
                        <div class="form-group row mb-0">
                            <label class="col-lg-4 col-form-label">Url</label>
                            <div class="col-lg-8">
                                <input type="text" class="form-control form-control-sm" id="url" name="url" placeholder="Enter Name" value=""/>
                            </div>
                        </div>
                    </div>
                    <div class="mb-2">
                        <div class="form-group row mb-0">
                            <label class="col-lg-4 col-form-label">Icon</label>
                            <div class="col-lg-8">
                                <select class="form-control form-control-sm select2" id="icon" name="icon" style="width: 100%;">
                                  <option value="" selected>Chose Icon</option>
                                   @isset ($menu_icon)
                                     @foreach($menu_icon as $icon)
                                      <option value="{{ $icon->id }}" data-image="{{ asset($icon->icon_url) }}"></option>
                                     @endforeach
                                   @endisset
                               </select>
                            </div>
                        </div>
                    </div>
                    <div class="mb-1">
                        <div class="form-group row mb-0">
                            <label class="col-lg-4 col-form-label">Description</label>
                            <div class="col-lg-8">
                                <input type="text" class="form-control form-control-sm" id="description" name="description" placeholder="Enter Name" value=""/>
                            </div>
                        </div>
                    </div>
                    <div class="mb-2">
                        <div class="form-group row">
                            <label class="col-lg-4 col-form-label"></label>
                            <div class="col-lg-8">
                                <button type="submit" class="btn btn-success font-weight-bold">Save</button>
                                <button type="button" data-dismiss="modal" class="btn btn-danger">Cancel</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

{{-- Styles Section --}}
@section('styles')
<link rel="stylesheet" href="{{ config('app.url') }}global/vendor/datatables-bootstrap/dataTables.bootstrap.css">
<link rel="stylesheet" href="{{ config('app.url') }}global/vendor/datatables-responsive/dataTables.responsive.min.css">
<link rel="stylesheet" href="{{ config('app.url') }}plugins/custom/datatables/datatables.bundle.css">
<link rel="stylesheet" href="{{ config('app.url') }}css/inject.css">
@endsection

{{-- Scripts Section --}}
@section('scripts')
@include ('inc.confirm-delete-modal')
<script src="{{ config('app.url') }}global/vendor/datatables/jquery.dataTables.js"></script>
<script src="{{ config('app.url') }}global/vendor/datatables-bootstrap/dataTables.bootstrap.js"></script>
<script src="{{ config('app.url') }}global/vendor/datatables-responsive/dataTables.responsive.js"></script>
<script src="{{ config('app.url') }}css/inject.css"></script>
<script type="text/javascript">
  $(document).ready(function() {
    $('[data-switch=true]').bootstrapSwitch('state', true);
  });

  // loading data from array
  var data = [{
          id: 0,
          text: 'Pilih'
      }, {
          id: 1,
          text: 'Optional'
      }];
  $('.select2').select2();
  $(".select2").select2({
      templateResult: formatState,
      templateSelection: formatState
  });

  function formatState (opt) {
      if (!opt.id) {
          return opt.text;
      }

      var optimage = $(opt.element).attr('data-image');
      if(!optimage){
         return opt.text;
      } else {
          var $opt = $(
             '<span><img src="' + optimage + '" width="60px" /> ' + opt.text + '</span>'
          );
          return $opt;
      }
  };

  $('.datetimepicker-input').datetimepicker({
      format: 'dd-mm-yyyy hh:ii'
  });
  $('[data-switch=true]').bootstrapSwitch();
  var table = $('#datatable').dataTable({
    pageLength: 5,
    responsive: true,
    searchDelay: 800,
    processing: true,
    serverSide: true,
    select: true,
    searching: true,
    lengthMenu: [[5, 10, 25, 50, 100, 200, -1], [5, 10, 25, 50, 100, 200, "All"]],
    ajax: {
      method: 'POST',
      url : '{{ route('management.menu.data') }}',
      headers: {
        'X-CSRF-TOKEN': '{{ csrf_token() }}'
      }
    },
    columns: [
      {title: "No", data: 'DT_RowIndex', defaultContent: '-', class: 'text-center dt-body-nowrap', orderable: false, searchable: false, autoHide: false},
      {title: "Menu Name", data: 'name', defaultContent: '-', class: 'text-center dt-body-nowrap', autoHide: false},
      // {title: "Menu Icon", data: 'icon', defaultContent: '-', class: 'text-center dt-body-nowrap', autoHide: false},
      {title: "Menu Url", data: 'url', defaultContent: '-', class: 'text-center dt-body-nowrap', autoHide: false},
      {title: "Description", data: 'description', defaultContent: '-', class: 'text-center dt-body-nowrap', autoHide: false},
      {title: "Actions", data: 'action', orderable: false, class: 'text-center dt-body-nowrap', responsivePriority: -1},
    ],
    order: [[1, 'asc']],
    bStateSave: true,
    columnDefs: [
      {
        targets: [0,-1],
        className: 'text-center visible dt-body-nowrap'
      },
    ]
  });

  function show_data(id = "") {
      if (id !== "") {
          $.ajax({
              url: "{{ route('management.menu.store')}}/" + id,
              type: "GET",
              headers: {
                'X-CSRF-TOKEN': '{{ csrf_token() }}'
              },
              success: function (response) {
                  $("#form-input").attr("action", "{{ route('management.menu.update','')}}/"+id);
                  $('#form-input').trigger("reset");
                  $('#method').val("PUT");

                  $('#id').val(response.data.id);
                  $('#name').val(response.data.name);
                  $('#url').val(response.data.url);
                  $('#icon').val(response.data.icon).trigger('change');
                  $('#parent_id').val(response.data.parent_id).trigger('change').prop('disabled');;
                  $('#description').val(response.data.description);
                  $('#modal-form').modal('show');
                  $('#id').focus();
              },
              error: function (xhr, status, error) {
                  showDialog.show(xhr.status + " " + status + " " + error, false);
              }
          });
      } else {
          $("#form-input").attr("action", "{{ route('management.menu.store')}}");
          $('#form-input').trigger("reset");
          $('#method').val("POST");

          $('#id').focus();
          $('#modal-form').modal('show');
      }
  }

  function refresh_table() {
      $('#datatable').dataTable().ajax.reload();
  }

  function format_date(val) {
      var date_arr = val.split(" ");
      var time = date_arr[1];
      var date_id_arr = date_arr[0].split("-");
      var date_fix = date_id_arr[2] + "-" + date_id_arr[1] + "-" + date_id_arr[0];
      var date_transaction = date_fix + " " + time;
      return date_transaction;
  }
</script>
@endsection