src/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

 /*
  * These routes require no users to be logged in
  */

Route::get('/', 'HomeController@index');
Route::get('dashboard', 'HomeController@dashboard')->name('dashboard');
Route::get('/quick-search', 'PagesController@quickSearch')->name('quick-search');
Route::get('/noauth', 'HomeController@noauth')->name('noauth');

Route::middleware('web')->group(function() {
   Route::middleware('guest')->namespace('Auth')->group(function() {
      Route::get('/', 'LoginController@showLoginForm')->name('login.main');
     	Route::get('/login', 'LoginController@showLoginForm')->name('login.show-form');
      Route::get('/attribute', 'LoginController@attribute')->name('login.attribute');
     	Route::post('/login', 'LoginController@login')->name('login');
   });
   Route::get('/logout', 'Auth\LoginController@logout')->name('logout');
});

Route::middleware('web')->group(function() {
  Route::prefix('management')->namespace('Management')->as('management.')->group(function() {
      Route::prefix('user')->as('user.')->group(function() {
          Route::post('data', 'UserController@getData')->name('data');
          Route::delete('{id}', 'UserController@destroy')->name('show');
          Route::get('{id}', 'UserController@edit')->name('show');
          Route::get('{id}/change-password', 'UserController@changeOtherPassword')->name('other.change-password');
          Route::put('{id}/update-password', 'UserController@updateOtherPassword')->name('other.update-password');
      });
      Route::resource('user', 'UserController', ['except' => ['create', 'show']]);

     Route::get('login-history', 'UserHistoryController@showLoginHistory')->name('login-history');
     Route::post('login-history/data', 'UserHistoryController@getLoginHistoryData')->name('login-history.data');

     Route::prefix('role')->as('role.')->group(function() {
         Route::post('data', 'RoleController@getData')->name('data');
         Route::get('{id}', 'RoleController@show')->name('show');
         Route::get('auth/{id}', 'RoleController@show_auth')->name('show.auth');
         Route::post('{id}/{col}/{val}', 'RoleController@update_auth')->name('update.auth');
     });
     Route::resource('role', 'RoleController', ['except' => ['create', 'show']]);

     Route::prefix('menu')->as('menu.')->group(function() {
         Route::post('data', 'MenuController@getData')->name('data');
         Route::get('{id}', 'MenuController@show')->name('show');
     });
     Route::resource('menu', 'MenuController', ['except' => ['create', 'show']]);

     Route::prefix('company-auth')->as('company-auth.')->group(function() {
         Route::get('{company_id}', 'CompanyAuthController@getData')->name('data');
         Route::post('{id}/{sts}', 'CompanyAuthController@update')->name('update');
     });
     Route::resource('company-auth', 'CompanyAuthController', ['except' => ['create']]);
  });
});


$router->group(['prefix' => 'reports', 'namespace' => 'Reports', 'middleware' => 'auth'], function () use ($router) {
    $router->group(['prefix' => '{table}'], function () use ($router) {
        $router->get('/{import}/import', [
            'as' => 'reports.import', 'uses' => 'ReportsController@import'
        ]);
        $router->get('/{export}/view', [
            'as' => 'reports.view', 'uses' => 'ReportsController@view'
        ]);
        $router->get('/{export}/download', [
            'as' => 'reports.download', 'uses' => 'ReportsController@download'
        ]);
    });
});

$router->group(['prefix' => 'elastic-serach', 'namespace' => 'Search'], function () use ($router) {
    $router->group(['prefix' => '{table}'], function () use ($router) {
        $router->get('list', [
            'as' => 'search.list', 'uses' => 'SearchController@list'
        ]);
        $router->get('/data', [
            'as' => 'search.data', 'uses' => 'SearchController@data'
        ]);
    });
});

$router->group(['prefix' => 'master', 'namespace' => 'Master', 'middleware' => 'auth'], function () use ($router) {
    $router->group(['prefix' => '{table}'], function () use ($router) {
        $router->get('/', [
            'as' => 'master.index', 'uses' => 'MasterController@index'
        ]);
        $router->post('list', [
            'as' => 'master.list', 'uses' => 'MasterController@list'
        ]);
        $router->get('list', [
            'as' => 'master.list', 'uses' => 'MasterController@list'
        ]);
        $router->get('data/{id}', [
            'as' => 'master.data', 'uses' => 'MasterController@data'
        ]);
        $router->post('/', [
            'as' => 'master.save', 'uses' => 'MasterController@save'
        ]);
        $router->put('/{id}', [
            'as' => 'master.update', 'uses' => 'MasterController@update'
        ]);
        $router->delete('{id}', [
            'as' => 'master.delete', 'uses' => 'MasterController@delete'
        ]);
    });
});

 $router->group(['prefix' => 'clinic', 'namespace' => 'Clinic', 'middleware' => 'auth'], function () use ($router) {
     $router->group(['prefix' => '{table}'], function () use ($router) {
         $router->get('/', [
             'as' => 'clinic.index', 'uses' => 'ClinicController@index'
         ]);
         $router->post('list', [
             'as' => 'clinic.list', 'uses' => 'ClinicController@list'
         ]);
         $router->get('list', [
             'as' => 'clinic.list', 'uses' => 'ClinicController@list'
         ]);
         $router->get('data/{id}', [
             'as' => 'clinic.data', 'uses' => 'ClinicController@data'
         ]);
         $router->post('save', [
             'as' => 'clinic.save', 'uses' => 'ClinicController@save'
         ]);
         $router->post('update/{id}', [
             'as' => 'clinic.update', 'uses' => 'ClinicController@update'
         ]);
         $router->delete('{id}', [
             'as' => 'clinic.delete', 'uses' => 'ClinicController@delete'
         ]);
     });
 });

 $router->group(['prefix' => 'product', 'namespace' => 'Product'], function () use ($router) {
     $router->group(['prefix' => '{table}'], function () use ($router) {
         $router->get('/', [
             'as' => 'product.index', 'uses' => 'ProductController@index'
         ]);
         $router->post('list', [
             'as' => 'product.list', 'uses' => 'ProductController@list'
         ]);
         $router->get('list', [
             'as' => 'product.list', 'uses' => 'ProductController@list'
         ]);
         $router->get('data/{id}', [
             'as' => 'product.data', 'uses' => 'ProductController@data'
         ]);
         $router->post('save', [
             'as' => 'product.save', 'uses' => 'ProductController@save'
         ]);
         $router->post('update/{id}', [
             'as' => 'product.update', 'uses' => 'ProductController@update'
         ]);
         $router->delete('{id}', [
             'as' => 'product.delete', 'uses' => 'ProductController@delete'
         ]);
     });
 });

  $router->group(['prefix' => 'advertising', 'namespace' => 'Advertising'], function () use ($router) {
      $router->group(['prefix' => '{table}'], function () use ($router) {
          $router->get('/', [
              'as' => 'advertising.index', 'uses' => 'AdvertisingController@index'
          ]);
          $router->post('list', [
              'as' => 'advertising.list', 'uses' => 'AdvertisingController@list'
          ]);
          $router->post('detail', [
              'as' => 'advertising.detail', 'uses' => 'AdvertisingController@detail'
          ]);
          $router->get('data/{id}', [
              'as' => 'advertising.data', 'uses' => 'AdvertisingController@data'
          ]);
          $router->post('save', [
              'as' => 'advertising.save', 'uses' => 'AdvertisingController@save'
          ]);
          $router->post('update/{id}', [
              'as' => 'advertising.update', 'uses' => 'AdvertisingController@update'
          ]);
          $router->delete('{id}', [
              'as' => 'advertising.delete', 'uses' => 'AdvertisingController@delete'
          ]);
      });
  });

  $router->group(['prefix' => 'sales', 'namespace' => 'Sales'], function () use ($router) {
      $router->group(['prefix' => '{table}'], function () use ($router) {
          $router->get('/', [
              'as' => 'sales.index', 'uses' => 'SalesController@index'
          ]);
          $router->post('list', [
              'as' => 'sales.list', 'uses' => 'SalesController@list'
          ]);
          $router->post('detail', [
              'as' => 'sales.detail', 'uses' => 'SalesController@detail'
          ]);
          $router->get('data/{id}', [
              'as' => 'sales.data', 'uses' => 'SalesController@data'
          ]);
          $router->post('save', [
              'as' => 'sales.save', 'uses' => 'SalesController@save'
          ]);
          $router->post('update/{id}', [
              'as' => 'sales.update', 'uses' => 'SalesController@update'
          ]);
          $router->delete('{id}', [
              'as' => 'sales.delete', 'uses' => 'SalesController@delete'
          ]);
          $router->post('{id}', [
              'as' => 'sales.cancel', 'uses' => 'SalesController@cancel'
          ]);
      });
  });

 $router->group(['prefix' => 'warehouse', 'namespace' => 'Warehouse'], function () use ($router) {

src/app/Models/User.php
<?php

namespace App\Models;

use Session, Auth;
use App\Models\Role;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable, SoftDeletes;

    // protected $fillable = ['name', 'email', 'password'];
    protected $hidden = ['password', 'remember_token'];

    protected $revisionCreationsEnabled = true;
    protected $dontKeepRevisionOf = ['password', 'last_login', 'remember_token'];

    protected $primaryKey = 'id';

    public $incrementing = false;

    // In Laravel 6.0+ make sure to also set $keyType
    protected $keyType = 'string';

    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('active', function(Builder $builder) {
            $builder->where('users.active', 1);
        });
    }

    public function findForPassport($username)
    {
       return self::where(filter_var($username, FILTER_VALIDATE_EMAIL) ? 'email' : 'username', $username)->first();
    }

    public function role() {
        return $this->belongsTo(Role::class);
    }
}

src/app/Http/Controllers/Management/CompanyAuthController.php
<?php

namespace App\Http\Controllers\Management;

use DataTables;
use Illuminate\Http\Request;
use App\Models\CompanyAuth;
use App\Http\Resources\Master\Company;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;

class CompanyAuthController extends Controller {

    public function update($id, $sts, Request $request) {
        // $module = $this->save($request);
        $data = CompanyAuth::find(str_replace('%20', ' ', $id));
        if(!$data){
          return makeResponse(200, 'error', 'fails', 'company not found!');
        }
        $data["status"] = $sts;
        $module = $data->save();
        if(!$sts){
            return makeResponse(200, 'success', 'notif_success', 'Update Company Auth '. $data->company_child .' has been disable join!');
        }
        return makeResponse(200, 'success', 'notif_success', 'Update Company Auth '. $data->company_child .' has been success join!');
    }

    public function getData($com_id, Request $request) {
         $select = Company::select(array(\DB::raw('CONCAT("'.$com_id.'","-",mst_company.id) AS id'),\DB::raw('"'.$com_id.'" AS company_id'),'mst_company.id AS company_child'))
                       ->leftJoin('company_auth', function($leftJoin)use($com_id){
                            $leftJoin->on('mst_company.id', '=', 'company_auth.company_child');
                            $leftJoin->where('company_auth.company_id',$com_id);
                        })
                        ->where('company_auth.company_id',null);
         $bindings = $select->getBindings();
         // dd(getSql($select));
         $insertQuery = 'INSERT into company_auth (company_auth.id,company_auth.company_id,company_auth.company_child) '
                        .$select->toSql();
         \DB::insert($insertQuery, $bindings);

      	$datas = CompanyAuth::select(
                        'company_auth.id',
                        'company_auth.company_id',
                        'company_auth.company_child',
                        'company_auth.status',
                        'mst_company.name as company_name'
                      )
                       ->leftJoin('mst_company', function($join){
                            $join->on('mst_company.id', '=', 'company_auth.company_child');
                        })
                       ->where('mst_company.id',"!=",'DEV')
                       ->where('company_auth.company_id',$com_id)
                       ->orderby('company_auth.company_child','ASC')
                       ->get();
        return makeResponse(200, 'success', null, $datas);
     }

     public function save($request, $data = null) {
        if (is_null($data)) {
            $data = new CompanyAuth;
        }

        if ($request->id) {
            $data->id = $request->id;
        }
        if ($request->company_id) {
            $data->company_id = $request->company_id;
        }
        if ($request->company_child) {
            $data->company_child = $request->company_child;
        }
        $data->save();

        return $data;
    }

}

src/app/Http/Controllers/Management/UserHistoryController.php
<?php

namespace App\Http\Controllers\Management;

use DataTables;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\UserLoginHistory;

class UserHistoryController extends Controller {
    public function showLoginHistory(){
        $page_title = 'User Login History';
        $page_description = 'Home/User Management/User Login History';

        return view('management.user.login-history', compact('page_title', 'page_description'));
    }

    public function getLoginHistoryData(){
        $userLoginHistory = UserLoginHistory::with('user')->select('user_login_histories.*');
        return Datatables::of($userLoginHistory)
            ->editColumn('created_at', function($userLoginHistory) {
                return $userLoginHistory->created_at->format('d M Y H:i:s');
            })
            ->make(true);
    }
}

src/resources/views/management/user/change-password.blade.php
@extends('layout.default')

@section('content')
	<div class="card card-custom body-container">
        @include('inc.error-list')
        @include('inc.success-notif')
	    <form class="form" action="{{ isset($id) ? route('management.user.other.update-password', $id) : route('management.user.update-password') }}" method="POST">
	    	{!! csrf_field() !!}
	        {!! method_field('PUT') !!}
	        <div class="card-header border-1 pt-6 pb-0">
	            <div class="card-title">
	                <h3 class="card-label">Edit User
	                </h3>
	            </div>
	        </div>
	        <div class="card-body">
	            <div class="form-group row">
	                <div class="col-lg-12">
	                    <label>Name:</label>
	                    <input type="text" class="form-control" name="name" value="{{ old('name') }}" placeholder="Enter Name" required />
	                    <span class="form-text text-muted">Please enter your Name</span>
	                </div>
	                <div class="col-lg-12">
	                    <label>Email</label>
	                    <input type="email" class="form-control" name="email" value="{{ old('email') }}" placeholder="Enter Email" required />
	                    <span class="form-text text-muted">Please enter your Email</span>
	                </div>
	                <div class="col-lg-12">
	                    <label>Username:</label>
	                    <div class="input-group">
	                        <div class="input-group-prepend"><span class="input-group-text"><i class="la la-user"></i></span></div>
	                        <input type="text" class="form-control" name="username" value="{{ old('username') }}" placeholder="Enter Username" required/>
	                    </div>
	                    <span class="form-text text-meted">Please enter your username</span>
	                </div>
	            </div>
	        </div>
	        <div class="card-footer">
	            <div class="row">
	                <div class="col-lg-12 text-right">
	                    <button type="submit" class="btn btn-primary">Update Password</button>
	                </div>
	            </div>
	        </div>
	    </form>
	</div>
@endsection


@section('styles')
@endsection

@section('scripts')
@endscript

src/resources/views/management/user/login-history.blade.php
@extends('layout.default')

@section('content')
<div class="subheader py-2 {{ Metronic::printClasses('subheader', false) }}" id="kt_subheader">
  <div class="{{ Metronic::printClasses('subheader-container', false) }} d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
    <div class="d-flex align-items-baseline flex-wrap mr-5">
      <h5 class="text-dark font-weight-bold my-1 mr-5">
        User History
      </h5>
      <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
        <li class="breadcrumb-item">
          <a href="{{ route('dashboard') }}" class="text-muted">Dashboard</a>
        </li>
        <li class="breadcrumb-item">
          <a href="{{ route('management.login-history') }}" class="text-muted">User History</a>
        </li>
        <li class="breadcrumb-item">
          <a href="#view" class="text-muted">View</a>
        </li>
      </ul>
    </div>
  </div>
</div>

@include('inc.error-list')
@include('inc.success-notif')
@include('inc.danger-notif')
<div class="card card-custom body-container">
  <div class="card-header bg-danger flex-wrap border-1 pt-1 pb-0 mb-2" style="min-height: 0;">
    <div class="card-title pt-1 pb-1">
      <h3 class="card-label font-weight-bolder text-white">User History
        <div class="text-muted pt-2 font-size-lg">show Datatable from table User History</div>
      </h3>
    </div>
    <div class="card-toolbar pt-1 pb-0">
      <div class="dropdown dropdown-inline">
          <button type="button" class="btn btn-tool btn-lg" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="la la-download text-white"></i> Tools
          </button>
          <div class="dropdown-menu dropdown-menu-sm dropdown-menu-right">
              <ul class="navi flex-column navi-hover py-2" id="btn_tools">
                  <li class="navi-header font-weight-bolder text-uppercase font-size-xs text-primary pb-2">
                      Export Tools
                  </li>
                  <li class="navi-item">
                      <a href="javascript:;" data-action="0" class="navi-link tool-action" id="export_print">
                          <span class="navi-icon"><i class="la la-print"></i></span>
                          <span class="navi-text">Print</span>
                      </a>
                  </li>
                  <li class="navi-item">
                      <a href="javascript:;" data-action="1" class="navi-link tool-action" id="export_copy">
                          <span class="navi-icon"><i class="la la-copy"></i></span>
                          <span class="navi-text">Copy</span>
                      </a>
                  </li>
                  <li class="navi-item">
                      <a href="javascript:;" data-action="2" class="navi-link tool-action" id="export_pdf">
                          <span class="navi-icon"><i class="la la-file-pdf-o"></i></span>
                          <span class="navi-text">PDF</span>
                      </a>
                  </li>
                  <li class="navi-item">
                      <a href="javascript:;" data-action="3" class="navi-link tool-action" id="export_excel">
                          <span class="navi-icon"><i class="la la-file-excel-o"></i></span>
                          <span class="navi-text">Excel</span>
                      </a>
                  </li>
                  <li class="navi-item">
                      <a href="javascript:;" data-action="4" class="navi-link tool-action" id="export_csv">
                          <span class="navi-icon"><i class="la la-file-text-o"></i></span>
                          <span class="navi-text">CSV</span>
                      </a>
                  </li>
                  <li class="navi-item">
                      <a href="javascript:;" data-action="5" class="navi-link tool-action" id="export_reload">
                          <span class="navi-icon"><i class="la la-file-pdf-o"></i></span>
                          <span class="navi-text">RELOAD</span>
                      </a>
                  </li>
              </ul>
          </div>
      </div>
    </div>
  </div>
  <div class="card-body pt-1">
    <table class="table table-bordered table-hover w100" cellspacing="0" id="datatable" style="width: 1070px !important;"></table>
  </div>
</div>

@endsection

{{-- Styles Section --}}
@section('styles')
<link rel="stylesheet" href="{{ config('app.url') }}global/vendor/datatables-bootstrap/dataTables.bootstrap.css">
<link rel="stylesheet" href="{{ config('app.url') }}global/vendor/datatables-responsive/dataTables.responsive.min.css">
<link rel="stylesheet" href="{{ config('app.url') }}plugins/custom/datatables/datatables.bundle.css">
<link rel="stylesheet" href="{{ config('app.url') }}css/inject.css">
@endsection

{{-- Scripts Section --}}
@section('scripts')
@include ('inc.confirm-delete-modal')
<script src="{{ config('app.url') }}global/vendor/datatables/jquery.dataTables.js"></script>
<script src="{{ config('app.url') }}global/vendor/datatables-bootstrap/dataTables.bootstrap.js"></script>
<script src="{{ config('app.url') }}global/vendor/datatables-responsive/dataTables.responsive.js"></script>
<script type="text/javascript">
  var start_date = "";
  var end_date = "";
  $(document).ready(function() {
    $("#datatable_wrapper").removeClass("dataTables_wrapper form-inline dt-bootstrap no-footer");
    $("#datatable_wrapper").addClass("dataTables_wrapper dt-bootstrap4 no-footer");
    $("div.datesearchbox").html('<div class="input-group"> <div class="input-group-addon"> <i class="glyphicon glyphicon-calendar"></i> </div><input type="text" class="form-control pull-right" id="datesearch" placeholder="Search by date range"> </div>');
    document.getElementsByClassName("datesearchbox")[0].style.textAlign = "center";
    $("#datesearch").attr("readonly",true);
    $('#datesearch').daterangepicker({
       autoUpdateInput: false
     });

      $('#datesearch').on('apply.daterangepicker', function(ev, picker) {
         $(this).val(picker.startDate.format('DD-MM-YYYY') + ' - ' + picker.endDate.format('DD-MM-YYYY'));
         start_date=picker.startDate.format('YYYY-MM-DD');
         end_date=picker.endDate.format('YYYY-MM-DD');
         refresh_table();
      });

      $('#datesearch').on('cancel.daterangepicker', function(ev, picker) {
        $(this).val('');
        start_date='';
        end_date='';
        refresh_table();
      });
  });

  $('[data-switch=true]').bootstrapSwitch('state', true);
  $('#Status').on('switchChange.bootstrapSwitch', function (event, state) {
      var x = $(this).data('on-text');
      var y = $(this).data('off-text');
      if ($("#Status").is(':checked')) {
          $(".is_reqs").hide(500);
      } else {
          $(".is_reqs").show(500);
      }
  });

  $('.select2').select2();

  $('.datetimepicker-input').datetimepicker({
      format: 'dd-mm-yyyy hh:ii'
  });
  $('[data-switch=true]').bootstrapSwitch();
  var table = $('#datatable').dataTable({
    pageLength: 5,
    responsive: true,
    searchDelay: 800,
    processing: true,
    serverSide: true,
    select: true,
    searching: true,
    lengthMenu: [[5, 10, 25, 50, 100, 200, -1], [5, 10, 25, 50, 100, 200, "All"]],
		ajax: {
				method: 'POST',
				url : '{{ route('management.login-history.data') }}',
				headers: {
						'X-CSRF-TOKEN': '{{ csrf_token() }}'
				}
		},
		columns : [
				{ title: 'Login at', data : 'created_at', name: 'created_at', class: 'text-center', defaultContent: '-', class: 'text-center dt-body-nowrap'},
				{ title: 'Username', data : 'user.username', name: 'user.username', class: 'text-center', defaultContent: '-', class: 'text-center dt-body-nowrap'},
				{ title: 'IP Address', data : 'ip', name: 'ip', class: 'text-center', defaultContent: '-', class: 'text-center dt-body-nowrap'},
				{ title: 'Browser', data : 'browser', name: 'browser', class: 'text-center', defaultContent: '-', class: 'text-center dt-body-nowrap'},
				{ title: 'Platform', data : 'platform', name: 'platform', class: 'text-center', defaultContent: '-', class: 'text-center dt-body-nowrap'},
		],
    order: [[1, 'asc']],
    bStateSave: true,
    dom:  "<'row'<'col-sm-4'l><'col-sm-5' <'datesearchbox'>><'col-sm-3'f>>" +
          "<'row'<'col-sm-12'tr>>" +
          "<'row'<'col-sm-5'i><'col-sm-7'p>>",
    columnDefs: [
      {
        targets: [0,-1],
        className: 'text-center dt-body-nowrap'
      },
    ],
    buttons: [
      {
        extend: 'print',
        text: 'Print current page',
        autoPrint: true,
        customize: function (win) {
          $(win.document.body)
          .css('font-size', '10pt')
          .prepend(
            '<img src="http://datatables.net/media/images/logo-fade.png" style="position:absolute; top:0; left:0;" />'
          );
          $(win.document.body).find('table')
          .addClass('compact')
          .css('font-size', 'inherit');
        },
        exportOptions: {
          columns: [0, 1, 'visible'],
          modifier: {
            page: 'current'
          },
        }
      }, {
        extend: 'copy',
        className: 'btn default',
        exportOptions: {
          columns: [0, 1, 'visible']
        }
      }, {
        extend: 'pdf',
        className: 'btn default',
        exportOptions: {
          columns: [0, 1, 'visible']
        }
      }, {
        extend: 'excelHtml5',
        className: 'btn default',
        excelStyles: {
          template: 'blue_medium',
        },
        exportOptions: {
          columns: [0, 1, 'visible']
        }
      }, {
        extend: 'csvHtml5',
        className: 'btn default',
        exportOptions: {
          columns: [0, 1, 'visible']
        }
      }, {
        text: 'Reload',
        className: 'btn default',
        action: function (e, dt, node, config) {
          dt.ajax.reload();
          alert_show('Datatable reloaded!', false);
        }
      },
      'colvis'
    ],
  });
  $('#btn_tools > li > a.tool-action').on('click', function () {
      var action = $(this).attr('data-action');
      table.dataTable().button(action).trigger();
  });
</script>
@endsection